[package]
name = "rustling-ml"
version = "0.5.0"
authors = ["hdlj <hubert.delajonquiere@snips.net>", "Mathieu Poumeyrol <kali@zoy.org>"]

[dependencies]
error-chain = { version="0.10", default-features=false }
fnv = "1.0"
serde = "1.0"
serde_derive = "1.0"
