[package]
name = "rustling-ml"
version = "0.1.0"
authors = ["hdlj <hubert.delajonquiere@snips.net>", "Mathieu Poumeyrol <kali@zoy.org>"]

[dependencies]
error-chain = { version="0.10", default-features=false }
