[package]
name = "rustling-cli"
version = "0.1.0"
authors = ["hdlj <hubert.delajonquiere@snips.net>", "Mathieu Poumeyrol <kali@zoy.org>"]

[dependencies]
rustling = { path = ".."}
rustling-ontology = { path = "../ontology"}
prettytable-rs = "0.6"
clap = "2"
